name: Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Build docs
        run: |
          cd docs
          pipenv install
          pipenv run make html
          cd ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/_build/html
